pipelines:
  default:
    - step:
        name: Lint translations
        image: ghcr.io/borisnliscool/translate-tool:latest
        services:
          - docker
        script:
          # remove this if you do not have a configuration file
          - cp tt.config.json /tt.config.json
          - cp -r static/i18n/* /translations/
          - translate-tool validate
