jobs:
  lint-translations:
    name: Lint translations
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/borisnliscool/translate-tool:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare translations
        run: |
          # remove this if you do not have a configuration file
          cp tt.config.json /tt.config.json
          cp -r /static/i18n/* /translations/

      - name: Validate translations
        run: translate-tool validate
