name: Build & Release CLI

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  cicd:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/translate-tool && mv target/release/translate-tool target/release/translate-tool_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/translate-tool_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}